### ISSUE TITLE
User feedback per question

### ISSUE THREAD

**Issue by maxsv0** [maxsv0/mega-iq-ui#102]
Provide a possibility for the user to vote for the quality of questions of a test that he has passed.
* classroom seems the most appropriate place for this feature
* allow a user to vote with a star in range 1-5
* after the user voted, provide a possibility to write a text comment and submit it together with a rating.

I don't think there is a need to display this rating on the website right now, it's mostly to determine questions quality and to change questions database accordingly.

**Comment by Aisangon** [comment]
@maxsv0 look at this, i could build this as a custom component https://www.cssscript.com/demo/simple-5-star-rating-system-with-css-and-html-radios/, it works with fontawesome. Do we need a new endpoint for this or how do you imagine this working for the backend?

**Comment by Aisangon** [comment]
I created the basic rating component for test result, when you can, you can create the api endpoint for it: this would be my request body, what do you think?

`   id: Answer["id"];
    score: number;
    comment: string;
    rated: boolean;`

if user has already rated the question, rated would just be true and couldn't submit rating again

**Comment by maxsv0** [comment]
API is not ready yet, I'll update when available.
Endpoint URL would be 
```https://www.mega-iq.com/api/v1/user/feedback```

method POST, Content-Type: application/json, user token is required.

example body:
```
{
  test: "dff26adf-1d7e-4d3e-9c36-b668612eb49a",
  question: 1,
  score: 5,
  comment: "simple comment"
}
```

```rated: boolean;``` is redundant cause we could allow users to vote as many times as they want.
id should be a question id, in fact not an id but a question number.
answerId API would extract from a DB having a test code and question number.

**Comment by Aisangon** [comment]
@maxsv0 okay i understand, so a user should be able to rate the same question again even when he might have already. how would the successful API response look like?

**Comment by maxsv0** [comment]
I think status code 200 is enough. 
No response body, just a status code 200 in the header.

**Comment by Aisangon** [comment]
@maxsv0 great, let me know when it's ready 👍

**Comment by maxsv0** [comment]
@Aisangon API updated, please try

**Comment by Aisangon** [comment]
@maxsv0 
![1](https://user-images.githubusercontent.com/37509874/80916966-473e6300-8d5c-11ea-97bc-c67f5f2a2e08.PNG)
![2](https://user-images.githubusercontent.com/37509874/80916972-558c7f00-8d5c-11ea-94e0-7cf962e16a3c.PNG)
