### ISSUE TITLE
Set Opengraph meta tags

### ISSUE THREAD

**Issue by Aisangon** [maxsv0/mega-iq-ui#103]
@maxsv0 Testing the social buttons, there is a bug causing the Pinterest social button not to open because `[autoSetMeta]="true"` on social button, Pinterest is looking for `<meta property="og:image" content=" />` which we don't have yet. Another possibility is to set `[image]` on social buttons selector. Question is if you have a specific image or should I find one? Possibly for FB and Twitter sharing this might be useful as well. That's why I opened this task.

To fix this Pinterest issue, should I had an og image or add `[image]` to `<share-buttons` selector? Do you have an image we can use or should I find something for now?

**Comment by maxsv0** [comment]
maybe it would be a good idea to set [autoSetMeta]="false" and specify tags manually.

anyway, the image should be set manually:

- homepage - top promo image
- user profile - user image (or certificate, if exists)
- IQ test details - iq test image, each has
- all IQ tests page - maybe homepage image

**Comment by Aisangon** [comment]
@maxsv0 "homepage - top promo image" which image you refer to?

**Comment by maxsv0** [comment]
@Aisangon this one
https://storage.googleapis.com/mega-iq/iqtest/bg-index.jpg

**Comment by Aisangon** [comment]
@maxsv0 ok thank you, so "top promo image" and "homepage image" you mean the same image right?

**Comment by maxsv0** [comment]
>  "top promo image" and "homepage image" you mean the same image right?
to @Aisangon,  yes!

Check for all pages.

1) Check that title is set. Should not something but not “Mega-IQ is loading..” 
2) Check that h1/h2/h3/h4/h5/h6 tags contains only relevant data
3) Check that keywords schema is used.
4) Check Opengraph meta tags: title, description, picture

**Comment by maxsv0** [comment]
Current status:

ES

URL | Title | h1/h2/.. | keywords
------------ | ------------- | ------------- | -------------
https://es.mega-iq.com/ | :white_check_mark:  | :white_check_mark: | :ballot_box_with_check:
https://es.mega-iq.com/iqtest | :ballot_box_with_check:  | :ballot_box_with_check: | :ballot_box_with_check:
https://es.mega-iq.com/iqtest/iq-practice | :ballot_box_with_check:  | :ballot_box_with_check: | :ballot_box_with_check:
https://es.mega-iq.com/iqtest/iq-standard | :ballot_box_with_check:  | :ballot_box_with_check: | :ballot_box_with_check:
https://es.mega-iq.com/iqtest/mega-iq | :ballot_box_with_check:  | :ballot_box_with_check: | :ballot_box_with_check:
https://es.mega-iq.com/iqtest/math | :ballot_box_with_check:  | :ballot_box_with_check: | :ballot_box_with_check:
https://es.mega-iq.com/iqtest/grammar | :ballot_box_with_check:  | :ballot_box_with_check: | :ballot_box_with_check:
https://es.mega-iq.com/login | :ballot_box_with_check:  | :ballot_box_with_check: | :ballot_box_with_check:
https://es.mega-iq.com/register | :ballot_box_with_check:  | :ballot_box_with_check: | :ballot_box_with_check:
https://es.mega-iq.com/forget | :ballot_box_with_check:  | :ballot_box_with_check: | :ballot_box_with_check:
https://es.mega-iq.com/home | :ballot_box_with_check:  | :white_check_mark: | :white_check_mark:
https://es.mega-iq.com/user/8 | :ballot_box_with_check:  | :ballot_box_with_check: | :ballot_box_with_check:
https://es.mega-iq.com/iqtest/result/13007a90-def2-4484-a29e-b93d13236e60 | :ballot_box_with_check:  | :ballot_box_with_check: | :ballot_box_with_check:
https://es.mega-iq.com/classroom/…..  | :ballot_box_with_check:  | :white_check_mark: | :white_check_mark:

EN

URL | Title | h1/h2/.. | keywords
------------ | ------------- | ------------- | -------------
https://www.mega-iq.com/ | :white_check_mark:  | :white_check_mark: | :white_check_mark:
https://www.mega-iq.com/iqtest | :white_check_mark:  | :white_check_mark: | :white_check_mark:
https://www.mega-iq.com/iqtest/iq-practice | :white_check_mark:  | :white_check_mark: | :white_check_mark:
https://www.mega-iq.com/iqtest/iq-standard | :white_check_mark:  | :white_check_mark: | :white_check_mark:
https://www.mega-iq.com/iqtest/mega-iq | :white_check_mark:  | :white_check_mark: | :white_check_mark:
https://www.mega-iq.com/iqtest/math | :white_check_mark:  | :white_check_mark: | :white_check_mark:
https://www.mega-iq.com/iqtest/grammar | :white_check_mark:  | :white_check_mark: | :white_check_mark:
https://www.mega-iq.com/login | :white_check_mark:  | :white_check_mark: | :x:
https://www.mega-iq.com/register | :white_check_mark:  | :white_check_mark: | :x:
https://www.mega-iq.com/forget | :white_check_mark:  | :white_check_mark: | :x:
https://www.mega-iq.com/home | :x:  | :white_check_mark: | :white_check_mark:
https://www.mega-iq.com/user/8 | :white_check_mark:  | :white_check_mark: | :white_check_mark:
https://www.mega-iq.com/iqtest/result/13007a90-def2-4484-a29e-b93d13236e60 | :white_check_mark:  | :white_check_mark: | :white_check_mark:
https://www.mega-iq.com/classroom/…..  | :x:  | :white_check_mark: | :white_check_mark:


RU

URL | Title | h1/h2/.. | keywords
------------ | ------------- | ------------- | -------------
https://ru.mega-iq.com/ | :white_check_mark:  | :white_check_mark: | :white_check_mark:
https://ru.mega-iq.com/iqtest | :white_check_mark:  | :white_check_mark: | :white_check_mark:
https://ru.mega-iq.com/iqtest/iq-practice | :white_check_mark:  | :white_check_mark: | :white_check_mark:
https://ru.mega-iq.com/iqtest/iq-standard | :white_check_mark:  | :white_check_mark: | :white_check_mark:
https://ru.mega-iq.com/iqtest/mega-iq | :white_check_mark:  | :white_check_mark: | :white_check_mark:
https://ru.mega-iq.com/iqtest/math | :white_check_mark:  | :white_check_mark: | :white_check_mark:
https://ru.mega-iq.com/iqtest/grammar | :white_check_mark:  | :white_check_mark: | :white_check_mark:
https://ru.mega-iq.com/login | :white_check_mark:  | :white_check_mark: | :x:
https://ru.mega-iq.com/register | :white_check_mark:  | :white_check_mark: | :x:
https://ru.mega-iq.com/forget | :white_check_mark:  | :white_check_mark: | :x:
https://ru.mega-iq.com/home | :x:  | :white_check_mark: | :white_check_mark:
https://ru.mega-iq.com/user/8 | :white_check_mark:  | :white_check_mark: | :white_check_mark:
https://ru.mega-iq.com/iqtest/result/13007a90-def2-4484-a29e-b93d13236e60 | :white_check_mark:  | :white_check_mark: | :white_check_mark:
https://ru.mega-iq.com/classroom/…..  | :x:  | :white_check_mark: | :white_check_mark:

**Comment by Aisangon** [comment]
@maxsv0 please check updated EN meta-tags https://docs.google.com/spreadsheets/d/1Clc5wMOupVqazz0kZ_7oZtL3dpBeRrzzWGE8LTv28yc/edit?usp=sharing. can be included in project?

**Comment by maxsv0** [comment]
@Aisangon yes, looks good!
