### ISSUE TITLE
User registration component

### ISSUE THREAD

**Issue by maxsv0** [maxsv0/mega-iq-ui#136]
Password field should have a button to show password
<img width="652" alt="Screenshot 2020-03-10 at 11 31 32" src="https://user-images.githubusercontent.com/3890266/76391606-1e0ee100-6370-11ea-90cd-c70dc4a59d59.png">

**Comment by Aisangon** [comment]
@maxsv0 check this article: https://uxmovement.com/forms/why-the-confirm-password-field-must-die/, what do you think? should we keep or remove password confirmation?
