### ISSUE TITLE
Create nice loader

### ISSUE THREAD

**Issue by maxsv0** [maxsv0/mega-iq-ui#14]
# 14 loaders

Different loader type:
- Initial page load
- page action: press button, submit answer
- file upload

Pages and list of loaders:
- /login (btn)
- /register (load GeoIP, file upload, submit)
- /forget (btn)
- /home (delete btn)
- /iqtest/iq-practice, and other (start test btn)
- /classroom/.. (submit answer, submit test)
- /settings (API data load, send verification, load GeoIP, file upload, submit)

**Comment by Aisangon** [comment]
one question for load GeoIP and file upload on /register, no file upload is present on page right now? and geoip response is too emidate for loader to be noticed, still implement it?

**Comment by maxsv0** [comment]
>  GeoIP and file upload on /register
was removed, no need in loader now

> geoip response is too emidate for loader to be noticed
Ok, feel free to remove current geoip loader or rework as needed.

**Comment by Aisangon** [comment]
can you check latest commit (cdefba9) from today in pull request? see if something needs to be changed or issue can be closed?

**Comment by maxsv0** [comment]
Please check my review comments in the pull request #27 (.gitignore and environment.ts)

**Comment by Aisangon** [comment]
I don't see the comments on gitignore or environment, but i will commit again without the firebase key and remove environments from gitignore as discussed. I hope it's all?

**Comment by Aisangon** [comment]
Commit done, 0e85546
