### ISSUE TITLE
Classroom - split Classroom and Test Review

### ISSUE THREAD

**Issue by maxsv0** [maxsv0/mega-iq-ui#149]
Test review is a component where a user could check an answer and hint for each question from a test that he passed.
Thus, Test Review should be blocked when a test is any status other than "FINISHED".

Right now:
1. classroom - https://www.mega-iq.com/classroom/1231d7a9-a5b5-42d5-bfd5-4c39897b7573
2. test result - https://www.mega-iq.com/iqtest/result/1231d7a9-a5b5-42d5-bfd5-4c39897b7573
3. classroom for review (blocked!) - https://www.mega-iq.com/classroom/1231d7a9-a5b5-42d5-bfd5-4c39897b7573

Should be
1. classroom - https://www.mega-iq.com/classroom/1231d7a9-a5b5-42d5-bfd5-4c39897b7573
2. test result - https://www.mega-iq.com/iqtest/result/1231d7a9-a5b5-42d5-bfd5-4c39897b7573
3. test review - https://www.mega-iq.com/iqtest/review/1231d7a9-a5b5-42d5-bfd5-4c39897b7573 

Extract all code that is needed for the FINISHED test to a Test Review component and remove it from the classroom.

**Comment by Aisangon** [comment]
> user could check an answer and hint for each question from a test that he passed.

@maxsv0 How is the hint displayed? Is this data already available?

**Comment by maxsv0** [comment]
@Aisangon  
yes. The field name is 'description' and it is available for user's finished tests.

here is how it is displayed:
<img width="933" alt="Screenshot 2020-05-10 at 10 24 14" src="https://user-images.githubusercontent.com/3890266/81494338-7434cd80-92a8-11ea-97ff-7933b6daa3bd.png">

**Comment by Aisangon** [comment]
@maxsv0 ok, i understand. you mention the test review should be blocked, how do you suggest it should work? I was thinking in showing a modal with the message that the review is blocked and it redirects you to home, what do you think?
