### ISSUE TITLE
Homepage UX/UI

### ISSUE THREAD

**Issue by maxsv0** [maxsv0/mega-iq-ui#3]
* draft UX attached
* create UX mockup first
* the first implementation of UI

**Comment by maxsv0** [comment]
![index-mockup](https://user-images.githubusercontent.com/3890266/55654078-ab58c580-57f0-11e9-89a1-b5993814879f.jpg)

**Comment by Aisangon** [comment]
based on ux draft attached in order see below

**Comment by Aisangon** [comment]
![home_image_2](https://user-images.githubusercontent.com/37509874/59130494-e487f000-896f-11e9-8a3b-162e5343e19a.PNG)
Hero page

**Comment by Aisangon** [comment]
counter would go there with call to action to start test, instead remove dropdown from navbar, animated navbar on scroll

**Comment by Aisangon** [comment]
next section on half left side best iq ranking https://codepen.io/hakura/pen/ebglw

**Comment by Aisangon** [comment]
![best_of_day](https://user-images.githubusercontent.com/37509874/59130647-53fddf80-8970-11e9-9bdd-cfbe1df017df.PNG)

right half side: profile of best iq of the day

**Comment by Aisangon** [comment]
after that section, add divider with counter animation
![counter_divider](https://user-images.githubusercontent.com/37509874/59130703-7859bc00-8970-11e9-9269-916ac8c6aec1.PNG)

**Comment by Aisangon** [comment]
next section iq test selection
![test section](https://user-images.githubusercontent.com/37509874/59130752-98897b00-8970-11e9-94d2-1474bd6b6165.PNG)

**Comment by Aisangon** [comment]
last section: footer. thoughts?

**Comment by maxsv0** [comment]
to @Aisangon 
Looks great!

> remove dropdown from navbar
I don't think this is possible since it's needed on other pages.

> counter would go there with call to action to start test
yes, but you can't have a single button "start test" since there are different test types.

**Comment by Aisangon** [comment]
ok i understand, i will leave the dropdown, i was thinking to have the button start test lead you to `/iqtest`, what do you think? or will that url be deprecated later? i will make a branch for the homepage and build out my design, we can then decide changes

**Comment by Aisangon** [comment]
another question, do we have a mega-iq logo?

**Comment by maxsv0** [comment]
>  i was thinking to have the button start test lead you to /iqtest

yes, this is a good idea.
so to have a big button on the top that leads to /iqtest and iq test selection in the bottom with links to specific tests.

/iqtest - is a page with a list of all types of iq tests and a short description. I think this page would evolve when the number of tests will increase.
next level is /iqtest/iq-practice - full description and button to start the test.

> i will make a branch for the homepage and build out my design.

yes, creating a branch is a good idea.
also, you can commit directly to this repository, it could be faster than updating your fork.

>  do we have a mega-iq logo?

Yes, I just shared an adobe cloud folder with you.

**Comment by Aisangon** [comment]
alright, i will make changes accordingly. for the adobe invite you sent me i have an empty folder?
can you add more users to the iq score ranking via api, so i can display some more on the table? maybe like 5 or 10? what should be the top? @maxsv0

**Comment by maxsv0** [comment]
@Aisangon 
seems you need to accept an invite first, it should be in your email.
yes, I will generate some results.

**Comment by Aisangon** [comment]
@maxsv0  thanks, i will check it out again later. just fyi, i will push an inital commit for the homepage-ui branch, i made some other improvements related to this and some refactoring too, i will build on top of that, in case you have some suggestions let me know

**Comment by Aisangon** [comment]
Can you give me current on this issue? What might be missing? Is the basic structure layout  there?

**Comment by maxsv0** [comment]
Index:
1) example profile change to a list of profiles(list of users will be sorted by IQ score)
no animation as for start.

2) fix the modal window.
Maybe disable the modal window, move it to separate branch

**Comment by Aisangon** [comment]
I'll move modal to local branch 'homepage-ui' and disable it when we megre to master, 
let me know when you have the api updated

**Comment by maxsv0** [comment]
API ready!

```
exampleProfiles: [

]
```

**Comment by Aisangon** [comment]
alright, i updated the code to accept the new array, can you add a couple profiles now? maybe 5 or more?

**Comment by maxsv0** [comment]
yes, I'm trying to import database sample

**Comment by Aisangon** [comment]
alright let me know, i already pushed the latest changes we talked about, as soon as you add the profiles to the db you should see them on the page right away

**Comment by maxsv0** [comment]
I uploaded some data from the production website.

**Comment by maxsv0** [comment]
Mockup:

![homepage](https://user-images.githubusercontent.com/3890266/62801377-e2fcb480-bae5-11e9-9bb6-ad14007fa32e.jpg)
