### ISSUE TITLE
Add nice font

### ISSUE THREAD

**Issue by Aisangon** [maxsv0/mega-iq-ui#36]
Find a nice font to use in entire website

**Comment by maxsv0** [comment]
Here are some options for fonts
- https://fonts.google.com/ - all free
- https://fonts.adobe.com/ - all free and all paid, I have an active subscription

**Comment by Aisangon** [comment]
https://fonts.google.com/specimen/Roboto
https://fonts.google.com/specimen/Raleway

@maxsv0 what do you think?
