### ISSUE TITLE
Display progress bar(s)

### ISSUE THREAD

**Issue by Aisangon** [maxsv0/mega-iq-ui#37]
I improved the ui of the test on the profile page, i added a progress bar and would be great to display the progress of every test, in order to do that i would need the value (`integer`) passed from the user test endpoint. I think you could create a calculation from the completed questions divided by total questions? And pass that percentage as a number value. If test is expired pass `null`?

**Comment by maxsv0** [comment]
I will add to each test field "stat" with such structure:

"test": {
..
"stat": {
    "totalQuestonCount": 8,
    "totalQuestonAnswer": 8,
    "totalQuestonCorrect": 6,
    "groups": {
        "grammar": 100,
        "horizons": 12,
        "logic": 100,
        "math": 61
    }
}

"groups" has 4 values, a percentage of correct in 4 groups of questions: Grammar, Logic, Math, and Horizons

for test type PRACTICE, "groups" are not shown.

while the test is in progress, only "totalQuestonCount" and "totalQuestonAnswer" are shown.

**Comment by Aisangon** [comment]
okay perfect, i can work with that, i'll close the issue when you added the response data?

**Comment by maxsv0** [comment]
great, let's use this issue for implementation also.

**Comment by Aisangon** [comment]
great!

**Comment by maxsv0** [comment]
Currently, there are 2 progress bars
- One for profile IQ level (not really working :))
<img width="473" alt="Screen Shot 2019-06-10 at 7 55 32 PM" src="https://user-images.githubusercontent.com/3890266/59215639-0379c280-8bba-11e9-855d-2aaeb941826b.png">

- Second for groups for a test
<img width="1125" alt="Screen Shot 2019-06-10 at 7 55 44 PM" src="https://user-images.githubusercontent.com/3890266/59215651-096fa380-8bba-11e9-9b2c-4b5619e2bbd1.png">

We can change and/or add more progress bars (for example, during the test to see how much is answered).
I think profile IQ level progress bar is not relevant anymore, I want to replace it with a more detailed nice graph. Groups graph looks nice, maybe we can display it in a different way.

**Comment by Aisangon** [comment]
Can you check the api for this one? I have only found the number of questions per test, but not answered questions or remaining questions. I think it's the IQ test service?
