### ISSUE TITLE
Language change dropdown will always navigate to the homepage

### ISSUE THREAD

**Issue by maxsv0** [maxsv0/mega-iq-ui#67]
click on language change dropdown will always navigate to the homepage
user should stay on the same page

**Comment by Aisangon** [comment]
fixed, another question: if user is on es settings page for example and changes locale, should he be directed to the same page of that new locale instead of home-page of new locale?

**Comment by maxsv0** [comment]
It would be nice to stay on the same page when changing a locale (so settings page in a different language). 
But not all pages will work since user authentication right now is different for every sub-domain.

The backup option is to redirect to the homepage after changing a locale. Also absolutely fine solution.

**Comment by Aisangon** [comment]
okay, then i guess i would leave it like this, right? if it is not 100% working for all pages then it might be more confusing for user i think
