### ISSUE TITLE
Font loading problem

### ISSUE THREAD

**Issue by maxsv0** [maxsv0/mega-iq-ui#69]
problem with font loading -> seems weight 500 not found

Platform: All

**Comment by Aisangon** [comment]
![500](https://user-images.githubusercontent.com/37509874/65817653-52e80b00-e20a-11e9-920f-7b62bf673a5c.PNG)

**Comment by Aisangon** [comment]
did you mean it's not found here or where?

**Comment by maxsv0** [comment]
yes

**Comment by Aisangon** [comment]
@maxsv0 but it is loading correctly right? or am i missing something?
