### ISSUE TITLE
User home - progress towards certificate is missing

### ISSUE THREAD

**Issue by maxsv0** [maxsv0/mega-iq-ui#76]

**Comment by Aisangon** [comment]
@maxsv0 for now progress is only showing if progress is less than 100, is this what this issue is about?

**Comment by maxsv0** [comment]
@Aisangon no, sorry for no description

It's about a fact, that the user has to answer 100 questions to unlock the IQ certificate (he has to pass test several times, could be different tests). It should be some nice progress bar near (or above) the example certificate. It could be on home, or both home and public profile.

So currently API doesn't return a total number that is needed and also doesn't return number for the current user. This has to be fixed.

**Comment by Aisangon** [comment]
@maxsv0 i now used a progress bar to display progress towards unlocking certificate, is there a way to get progress towards certificate dinamically via the frontend? how is the calculation of the progress towards certificate composed of?

**Comment by Aisangon** [comment]
![1](https://user-images.githubusercontent.com/37509874/69990158-70588e80-1545-11ea-94a2-b5aaf56708f8.PNG)

**Comment by Aisangon** [comment]
@maxsv0 also, should the answered questions be correctly answered questions or simply answered regardless of correct or incorrect?

**Comment by maxsv0** [comment]
@Aisangon currently it will calculate amount of correct answers. I added a task to update the API.

**Comment by maxsv0** [comment]
@Aisangon progress bar looks great!
(but the bottom case should never exist - in case of 100% bar is not displayed anymore, but the certificate is shown and IQ score)

**Comment by Aisangon** [comment]
@maxsv0 okay, i will remove the green bar case. should i already push the issue with placeholder data or should i want until you have the API ready and I use the data coming from there?

**Comment by maxsv0** [comment]
'certificateProgress' is available now for a user profile. Number, from 0 to 100

```
certificateProgress: 48
```


<img width="933" alt="Screen Shot 2019-12-08 at 12 28 21 PM" src="https://user-images.githubusercontent.com/3890266/70388777-78398800-19b6-11ea-8a3d-a1040d17933d.png">
