### ISSUE TITLE
User public - pre-loader problem

### ISSUE THREAD

**Issue by maxsv0** [maxsv0/mega-iq-ui#78]
* loading more items triggers general pre-loader
* page should not open before user info is loaded -> show pre-loader

**Comment by Aisangon** [comment]
@maxsv0 on page load, preloader is showing, how do i reproduce `loading more items triggers general pre-loader`?

**Comment by maxsv0** [comment]
@Aisangon 
Try this user - https://es.mega-iq.com/user/200
(maybe it was already fixed)

**Comment by Aisangon** [comment]
@maxsv0 thanks, i was able to reproduce this problem on that user and since the above commit i was not able see this problem again, please let me know in case otherwise
