### ISSUE TITLE
Serve static pages: privacy/policy/?…

### ISSUE THREAD

**Issue by maxsv0** [maxsv0/mega-iq-ui#8]
- need a solution to serve static HTML files
- define what pages are missing

**Comment by maxsv0** [comment]
need "About" page

**Comment by Aisangon** [comment]
how do i assign this task to myself? or do you have to do it?

**Comment by maxsv0** [comment]
Go to [Projects -> Milestone 1](https://github.com/maxsv0/mega-iq-ui/projects/1) and move ticket to "In progress" column

**Comment by Aisangon** [comment]
For Germany, probably an Imprint "Impressum" page is needed, for now about us and privacy policy makes sense

**Comment by Aisangon** [comment]
Any text already written for the about page?

**Comment by maxsv0** [comment]
I will share a google doc with page content.
Also please put a link to each of the new pages. Somewhere in a footer is a good place for now.

**Comment by Aisangon** [comment]
I added a link to the about static page to the footer of the main page, I hope that is what you meant :)

**Comment by maxsv0** [comment]
Yes, exactly.
Also pease check a URL, it should be an absolute path without domain (start with slash: href="/assets/s ... ")

**Comment by maxsv0** [comment]
https://drive.google.com/open?id=1OOm6cPbR3NNSSF7Wr_uhDm8vU124FbGl

**Comment by Aisangon** [comment]
I copied the content of the static pages in the google doc, just in case. Have you been able to enable navigation to the static pages?

**Comment by maxsv0** [comment]
Great!
Yes, navigation fixed - http://de.mega-iq.com/assets/static/about.html
(sometimes you need to clear browser cache to remove cached redirect)

There is a problem with header, since it is not static:
<img width="1165" alt="Screen Shot 2019-05-01 at 7 41 39 PM" src="https://user-images.githubusercontent.com/3890266/57032038-9b929c80-6c49-11e9-81d9-8f80182d3d15.png">

Solution could be to create static header or to render this page (maybe updating a routes)

**Comment by olgasv1** [comment]
![IMG_2832](https://user-images.githubusercontent.com/39739790/57099073-dd8c1300-6d1b-11e9-9330-9fa06bae9910.jpg)

**Comment by Aisangon** [comment]
@maxsv0 i don't fully understand the problem, right now there is no header the first element after body is just the navbar? is that causing problems?

**Comment by maxsv0** [comment]
![image](https://user-images.githubusercontent.com/3890266/57157910-3de58800-6de2-11e9-895c-4f521b752a24.png)

**Comment by Aisangon** [comment]
Oh I see, should I just leave out the current user for now? I will fix the dropdown

**Comment by maxsv0** [comment]
Dropdown requires a list of Iq tests that comes from back-end. 
Since header is static and not rendered, all Angular tags don't work (routerLink,  *ngIf, (click) and etc.).

In case we want to leave it static, we will need to update all links/texts inside static header and convert it to pure HTML. So on static pages user will never be logged. 

I did an update for about page content, feel free to add your photo, name and title :)

**Comment by Aisangon** [comment]
I understand so i would suggest, never log user on static pages (remove top right current user, login etc.) and href to the individual tests in the dropdown, what do you think? What happens if a user logged in and navigates to the static pages? does that create conflict?

**Comment by maxsv0** [comment]
@Aisangon Yes, I think it's a good idea.
User should have a possibility to go back, that's important. (maybe in the top right block just button/link "back" would be enough)

**Comment by Aisangon** [comment]
Alright, I will do that

**Comment by Aisangon** [comment]
Since I pulled your last commit i'm getting the below error and the main page is empty now, i checked and I don't have a firebase api key in the environment.ts files, could that be the issue?  do i have to get it from you? source: https://github.com/firebase/quickstart-js/issues/61
![err-firebase](https://user-images.githubusercontent.com/37509874/57191315-7e4d1f00-6f24-11e9-8007-0bbb09674378.PNG)

**Comment by Aisangon** [comment]
Works with firebase api key! Now getting error from mega-iq api? Do I need to update something else you changed?
![api-err](https://user-images.githubusercontent.com/37509874/57244496-c52c3900-7038-11e9-92a5-d2c1c238779e.PNG)

**Comment by maxsv0** [comment]
@Aisangon 
I just fixed a API to handle this requests. 
For local testing you should change apiUrl to http://de.mega-iq.com/api/v1  cause primary domain is not set yet.

**Comment by Aisangon** [comment]
@maxsv0 thank you, all working again now

**Comment by maxsv0** [comment]
Done.
