### ISSUE TITLE
Test on home is created twice after submussion

### ISSUE THREAD

**Issue by Aisangon** [maxsv0/mega-iq-ui#84]
To reproduce:
Start test -> Submit all and Submit test -> Test in home profile list is created 2, after reloading it appears correctly just once. In array only 1 test present.
![er](https://user-images.githubusercontent.com/37509874/66135164-ca96ab00-e5f9-11e9-945b-7a49b83a9ae4.PNG)
![er1](https://user-images.githubusercontent.com/37509874/66135172-cd919b80-e5f9-11e9-829a-421d8d15abde.PNG)

**Comment by Aisangon** [comment]
@maxsv0 should we close this issue?

**Comment by maxsv0** [comment]
seems ok
