### ISSUE TITLE
/settings, fix for 'Profile Background'

### ISSUE THREAD

**Issue by maxsv0** [maxsv0/mega-iq-ui#92]
![Screen-Shot-2019-12-01-at-10 20 20-PM](https://user-images.githubusercontent.com/3890266/69920507-37f37a80-1489-11ea-8fe2-af0b692c5334.jpg)

**Comment by Aisangon** [comment]
@maxsv0 can you explain what the bug is? :) is the number of background not correct with the color?

**Comment by maxsv0** [comment]
@Aisangon
it's not a bug in fact.
So instead of showing a number (7 on screenshot), the appropriate background should be highlighted (red border on a screenshot)

**Comment by maxsv0** [comment]
👍
