### ISSUE TITLE
/settings, get location bug

### ISSUE THREAD

**Issue by maxsv0** [maxsv0/mega-iq-ui#93]
1. The geolocation request should be triggered **only** when the location is **not set**. Right now seems request triggered every time.

2. Layout problem:  
![image](https://user-images.githubusercontent.com/3890266/69920703-5ce8ed00-148b-11ea-8b69-c7f32d388e75.png)

**Comment by Aisangon** [comment]
@maxsv0 when you mean location is not set you mean, `currentUser.location == null`? because this is happening already right? ` ngAfterViewInit() {
    if (this.isBrowser && this.currentUser.location == null) {
      this.detectLocation();
    }
  }`. Or am I missing something?

**Comment by maxsv0** [comment]
@Aisangon yes! 
the code is there, but it doesn't work in all cases.
maybe ngAfterViewInit should be changed to another hook.

**Comment by Aisangon** [comment]
@maxsv0 okay I understand now, i think it was becaue the form `oninit` was setting a location without checking if `null` and `ngAfterViewInit` was doing the detect loaction, i think that can reate conflict, i changed that part, i seems to get the location set properly for me, if you still encounter a problem, let me know how i can reproduce
