### ISSUE TITLE
Prepare for live

### ISSUE THREAD

**Issue by maxsv0** [maxsv0/mega-iq-ui#98]
Update: 11.01.20

QA:
- check direct register -> Working

- check social register  -> Working

- check pass each test type ->
Practice: Working
Standard: Working
Mega: Working
Grammar: Working
Math: Working

- check emails
- check all images for all questions
- check to receive a certificate
- check titles and h1/h2 on all pages
- check social share buttons
- check import

Cleanup code:
- remove dev tools: "submit all" button
- remove all debug output like console.log(..)

**Comment by Aisangon** [comment]
@maxsv0 no images for questions on dev. also new register shows `api service unavailable`, ist this enabled?

**Comment by maxsv0** [comment]
Hey, @Aisangon,
I'm working on images now, going to re-save all images for all locales according to the updated spreadsheet with questions/answers.

For google login, I have a [task in the API](https://github.com/maxsv0/mega-iq-api/issues/52), but  I'm not sure not if it is a back-end issue. Trying to fix this.

**Comment by Aisangon** [comment]
@maxsv0 thanks for the info, i'm trying to test all tests and when i click start test i get `{ok: false, msg: "Acceso denegado, accede a tu cuenta y prueba de nuevo", date: "2020-01-02T18:14:28.539+0000", locale: "ES"}
ok: false
msg: "Acceso denegado, accede a tu cuenta y prueba de nuevo"
date: "2020-01-02T18:14:28.539+0000"
locale: "ES"`, even though i'm logged in. Do you know why this could be?

**Comment by Aisangon** [comment]
testing social buttons i found an error 
![pin](https://user-images.githubusercontent.com/37509874/71685499-c6b12b00-2d98-11ea-89f2-57f6f550f53e.PNG), please quickly check #103 and let me know what you think?

**Comment by Aisangon** [comment]
@maxsv0 
![mess](https://user-images.githubusercontent.com/37509874/71685788-a170ec80-2d99-11ea-9415-e4bd1bef4fd1.PNG) FB Messenger not working.
![sharerurl](https://user-images.githubusercontent.com/37509874/71686325-2ad4ee80-2d9b-11ea-8133-0da3729d9c2e.PNG)
should be exclude for now or is very important?

**Comment by maxsv0** [comment]
@Aisangon  FB Messenger - exclude, if not working

> i'm logged in
Sorry forgot to tell, I recently deleted all users from the firebase and database, please create the user again.

**Comment by maxsv0** [comment]
two issues on user profile:
https://es.mega-iq.com/user/5

- certificate progress not displayed
- IQ badge is shown without number
![image](https://user-images.githubusercontent.com/3890266/71688621-763dcb80-2da0-11ea-810a-03e6ef0ec092.png)

**Comment by Aisangon** [comment]
@maxsv0 thanks for the info, i'll check this

**Comment by Aisangon** [comment]
@maxsv0 can you verify that in user profile API that IQ is not `null` on profile and that on `certificateProgress` is also not `null`? Progress bar only appears if `currentUser.certificateProgress < 100 && currentUser.certificateProgress !== null`. I will modify this.

**Comment by maxsv0** [comment]
Yes certificateProgress is set, seems a bug

<img width="292" alt="Screen Shot 2020-01-04 at 6 22 19 PM" src="https://user-images.githubusercontent.com/3890266/71769264-33eec880-2f1f-11ea-967a-00e278960ac0.png">

https://es.mega-iq.com/user/5

**Comment by Aisangon** [comment]
okay I see, I tested again, please check again in when in my pr
